/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
static const char *sp_sym_to_s(sp_sym id){(void)id;return "";}

static const char *sp_class_to_s(sp_Class c){(void)c;return "";}

static mrb_int sp_twice(void (*_block)(mrb_int, void*), void *_benv);

static mrb_int sp_twice(void (*_block)(mrb_int, void*), void *_benv) {
    SP_GC_SAVE();
    if (_block) _block(1LL, _benv);
    if (_block) _block(2LL, _benv);
    return 0;
  return 0;
}

int main(int argc,char**argv){
    SP_GC_SAVE();
    mrb_int lv_i = 0;

    lv_i = 1LL;
    printf("%lld\n", (long long)(lv_i * 100LL));
    lv_i = 2LL;
    printf("%lld\n", (long long)(lv_i * 100LL));
  return 0;
}
