/* Generated by Spinel AOT compiler */
#define SP_TU_NO_POLY_RENDER 1
#include "spinel_rt.h"
const sp_int sp_exc_subclass_count = 0;
const sp_int sp_exc_subclass_ids[] = { 0 };
#line 1 "<spinel-synthesized>"
#line 1 "<spinel-synthesized>"
static int _sp_main_argc; static char **_sp_main_argv; static int _sp_main_rc;
#line 1 "<spinel-synthesized>"
void _sp_main_body(void){
#line 1 "<spinel-synthesized>"
    SP_GC_SAVE();
#line 1 "<spinel-synthesized>"
    sp_int lv_big = 0;
#line 1 "<spinel-synthesized>"

#line 3 "main.rb"
  lv_big = 3000000000LL;
#line 4 "main.rb"
  { sp_int _t1 = sp_int_mul(lv_big, 2LL); if (_t1 == SP_INT_NIL) putchar('\n'); else printf("%lld\n", (long long)_t1); }
#line 5 "main.rb"
  { sp_int _t2 = sp_int_add(sp_int_pow(2LL, 40LL), 1LL); if (_t2 == SP_INT_NIL) putchar('\n'); else printf("%lld\n", (long long)_t2); }
#line 5 "main.rb"
  _sp_main_rc = 0;
#line 5 "main.rb"
}
#line 5 "main.rb"
int main(int argc,char**argv){
#line 5 "main.rb"
  _sp_main_argc = argc; _sp_main_argv = argv;
#line 5 "main.rb"
  sp_main_stack_run(_sp_main_body);
#line 5 "main.rb"
  return _sp_main_rc;
#line 5 "main.rb"
}
