/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
static const char *sp_sym_to_s(sp_sym id){(void)id;return "";}

static const char *sp_class_to_s(sp_Class c){(void)c;return "";}

static mrb_int sp_fib(mrb_int lv_n);

static mrb_int sp_fib(mrb_int lv_n) {
    SP_GC_SAVE();
    if ((lv_n < 2LL)) {
      return lv_n;
    } else {
      return (sp_fib((lv_n - 1LL)) + sp_fib((lv_n - 2LL)));
    }
  return 0;
}

int main(int argc,char**argv){
    SP_GC_SAVE();

    printf("%lld\n", (long long)sp_fib(20LL));
  return 0;
}
