/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
static const char *sp_sym_to_s(sp_sym id){(void)id;return "";}

/* sp_Class names table */
#define SP_CLASS_COUNT 23
static const char *const sp_class_names[23] = {(&("\xff" "BasicObject")[1]),(&("\xff" "Object")[1]),(&("\xff" "Kernel")[1]),(&("\xff" "Comparable")[1]),(&("\xff" "Enumerable")[1]),(&("\xff" "NilClass")[1]),(&("\xff" "TrueClass")[1]),(&("\xff" "FalseClass")[1]),(&("\xff" "Numeric")[1]),(&("\xff" "Integer")[1]),(&("\xff" "Float")[1]),(&("\xff" "String")[1]),(&("\xff" "Symbol")[1]),(&("\xff" "Array")[1]),(&("\xff" "Hash")[1]),(&("\xff" "Range")[1]),(&("\xff" "Time")[1]),(&("\xff" "Module")[1]),(&("\xff" "Class")[1]),(&("\xff" "Complex")[1]),(&("\xff" "Proc")[1]),(&("\xff" "Counter")[1]),(&("\xff" "Method")[1])};
static const char *sp_class_to_s(sp_Class c) __attribute__((unused));
static const char *sp_class_to_s(sp_Class c){if(c.cls_id>=0&&c.cls_id<SP_CLASS_COUNT)return sp_class_names[c.cls_id];return "";}
static mrb_bool sp_class_eq(sp_Class a, sp_Class b) __attribute__((unused));
static mrb_bool sp_class_eq(sp_Class a, sp_Class b){return a.cls_id == b.cls_id;}

typedef struct sp_Counter_s sp_Counter;

struct sp_Counter_s {
  mrb_int cls_id;
  mrb_int iv_count;
};

static sp_Counter *sp_Counter_new(mrb_int lv_start);
static inline void sp_Counter_initialize(sp_Counter *self, mrb_int lv_start);
static inline mrb_int sp_Counter_increment(sp_Counter *self);
static inline mrb_int sp_Counter_count(sp_Counter *self);

SP_POOL_DEFINE(Counter)
static inline sp_Counter *sp_Counter_new(mrb_int lv_start) {
  SP_GC_SAVE();
  sp_Counter *self = SP_POOL_NEW(Counter, NULL);
  self->cls_id = 21LL;
  SP_GC_ROOT(self);
  self->iv_count = lv_start;
  SP_GC_RESTORE();
  return self;
}

static inline void sp_Counter_initialize(sp_Counter *self, mrb_int lv_start) {
  self->iv_count = lv_start;
}

static inline mrb_int sp_Counter_increment(sp_Counter *self) {
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    self->iv_count += 1LL;
    return 0;
  return 0;
}

static inline mrb_int sp_Counter_count(sp_Counter *self) {
    SP_GC_SAVE();
    SP_GC_ROOT(self);
    return self->iv_count;
  return 0;
}

int main(int argc,char**argv){
    SP_GC_SAVE();
    sp_Counter *lv_c = NULL;
    SP_GC_ROOT(lv_c);

    lv_c = sp_Counter_new(10LL);
    for (mrb_int _t1 = 0; _t1 < 3LL; _t1++) {
        sp_redo_1: ;
      sp_Counter_increment(lv_c);
    }
    printf("%lld\n", (long long)lv_c->iv_count);
  return 0;
}
