/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
static const char *sp_sym_to_s(sp_sym id){(void)id;return "";}

static const char *sp_class_to_s(sp_Class c){(void)c;return "";}


int main(int argc,char**argv){
    SP_GC_SAVE();
    sp_StrArray *lv_words = NULL;
    SP_GC_ROOT(lv_words);
    const char *lv_w = (&("\xff")[1]);
    SP_GC_ROOT(lv_w);

    sp_StrArray *_t1 = sp_StrArray_new();
    sp_StrArray_push(_t1, (&("\xff" "spinel")[1]));
    sp_StrArray_push(_t1, (&("\xff" "compiles")[1]));
    sp_StrArray_push(_t1, (&("\xff" "ruby")[1]));
    lv_words = _t1;
    for (mrb_int _t2 = 0; _t2 < sp_StrArray_length(lv_words); _t2++) {
      const char * lv_w = sp_StrArray_get(lv_words, _t2);
        sp_redo_1: ;
      { const char *_ps = (const char *)(sp_str_upcase(lv_w)); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    }
    sp_StrArray * _t3 = lv_words;
    SP_GC_ROOT(_t3);
    sp_IntArray *_t4 = sp_IntArray_new();
    SP_GC_ROOT(_t4);
    for (mrb_int _t5 = 0; _t5 < sp_StrArray_length(_t3); _t5++) {
      const char *lv_w = sp_StrArray_get(_t3, _t5);
      sp_IntArray_push(_t4, sp_str_length(lv_w));
    }
    sp_IntArray * _t6 = _t4;
    SP_GC_ROOT(_t6);
    printf("%lld\n", (long long)sp_IntArray_sum(_t6, 0));
  return 0;
}
