/* Generated by Spinel AOT compiler */
#define SP_TU_NO_POLY_RENDER 1
#include "spinel_rt.h"
const sp_int sp_exc_subclass_count = 0;
const sp_int sp_exc_subclass_ids[] = { 0 };
#line 1 "<spinel-synthesized>"
#line 1 "<spinel-synthesized>"
static int _sp_main_argc; static char **_sp_main_argv; static int _sp_main_rc;
#line 1 "<spinel-synthesized>"
void _sp_main_body(void){
#line 1 "<spinel-synthesized>"
    SP_GC_SAVE();
#line 1 "<spinel-synthesized>"
    struct { sp_gc_frame_hdr h; void **p[2]; } _gcf = {{0, 2}}; SP_GC_ROOT_FRAME(_gcf);
#line 1 "<spinel-synthesized>"
    const char * lv_greeting = NULL;
#line 1 "<spinel-synthesized>"
    _gcf.p[0] = SP_GC_ENTRY_STR(lv_greeting);
#line 1 "<spinel-synthesized>"
    const char * lv_name = NULL;
#line 1 "<spinel-synthesized>"
    _gcf.p[1] = SP_GC_ENTRY_STR(lv_name);
#line 1 "<spinel-synthesized>"

#line 2 "main.rb"
  lv_greeting = ({ static struct { sp_str_hdr h; unsigned char m; char d[16]; } _fzl_0 = { { NULL, 16, 15, 0 }, 0xf1, "\343\201\223\343\202\223\343\201\253\343\201\241\343\201\257" }; _fzl_0.d; });
#line 3 "main.rb"
  lv_name = ({ static struct { sp_str_hdr h; unsigned char m; char d[7]; } _fzl_1 = { { NULL, 7 | SP_STR_SIZE_ASCII7, 6, 0 }, 0xf1, "spinel" }; _fzl_1.d; });
#line 4 "main.rb"
  { const char *_ps = (const char *)(({ const char *_t1 = (lv_greeting ?: sp_str_empty); SP_GC_ROOT(_t1); size_t _l1 = sp_str_byte_len(_t1); const char *_t2 = (lv_name ?: sp_str_empty); SP_GC_ROOT(_t2); size_t _l2 = sp_str_byte_len(_t2); size_t _cap3 = 4UL + _l1 + _l2; char *_t3 = sp_str_alloc_raw(_cap3 + 1); char *_t4 = _t3; memcpy(_t4, _t1, _l1); _t4 += _l1; memcpy(_t4, "\343\200\201", 3); _t4 += 3; memcpy(_t4, _t2, _l2); _t4 += _l2; memcpy(_t4, "!", 1); _t4 += 1; *_t4 = 0; sp_str_set_len(_t3, (size_t)(_t4 - _t3)); (const char *)_t3; })); sp_puts_str_line(_ps); }
#line 5 "main.rb"
  { sp_int _t5 = sp_str_length_m(lv_greeting); if (_t5 == SP_INT_NIL) putchar('\n'); else printf("%lld\n", (long long)_t5); }
#line 5 "main.rb"
  _sp_main_rc = 0;
#line 5 "main.rb"
}
#line 5 "main.rb"
int main(int argc,char**argv){
#line 5 "main.rb"
  _sp_main_argc = argc; _sp_main_argv = argv;
#line 5 "main.rb"
  sp_main_stack_run(_sp_main_body);
#line 5 "main.rb"
  return _sp_main_rc;
#line 5 "main.rb"
}
