/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
static const char *sp_sym_to_s(sp_sym id){(void)id;return "";}

static const char *sp_class_to_s(sp_Class c){(void)c;return "";}


int main(int argc,char**argv){
    SP_GC_SAVE();
    const char *lv_greeting = (&("\xff")[1]);
    SP_GC_ROOT(lv_greeting);
    const char *lv_name = (&("\xff")[1]);
    SP_GC_ROOT(lv_name);

    lv_greeting = (&("\xff" "こんにちは")[1]);
    lv_name = (&("\xff" "spinel")[1]);
    { const char *_ps = (const char *)(sp_sprintf("%s、%s!", lv_greeting, lv_name)); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    printf("%lld\n", (long long)sp_str_length(lv_greeting));
  return 0;
}
