/* Generated by Spinel AOT compiler */
#include "sp_runtime.h"
static const char *sp_sym_to_s(sp_sym id){(void)id;return "";}

static const char *sp_class_to_s(sp_Class c){(void)c;return "";}

static inline mrb_int sp_risky(mrb_int lv_n);

static inline mrb_int sp_risky(mrb_int lv_n) {
    SP_GC_SAVE();
    if ((lv_n > 2LL)) {
      sp_raise((&("\xff" "boom")[1]));
    }
    return (lv_n * 10LL);
  return 0;
}

int main(int argc,char**argv){
    SP_GC_SAVE();
    volatile const char *lv_e = (&("\xff")[1]);
    SP_GC_ROOT(lv_e);

    sp_exc_top++;
    if (setjmp(sp_exc_stack[sp_exc_top-1]) == 0) {
      printf("%lld\n", (long long)sp_risky(1LL));
      printf("%lld\n", (long long)sp_risky(5LL));
      sp_exc_top--;
    } else {
      sp_exc_top--;
      const char *_rescue_cls_1 = (const char *)sp_last_exc_cls;
      const char *_rescue_msg_1 = sp_exc_msg[sp_exc_top];
      lv_e = _rescue_msg_1;
      { const char *_ps = (const char *)(sp_sprintf("rescued: %s", lv_e)); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
    }
    { const char *_ps = (const char *)((&("\xff" "after")[1])); if (_ps) { fputs(_ps, stdout); if (!*_ps || _ps[strlen(_ps)-1] != '\n') putchar('\n'); } else putchar('\n'); }
  return 0;
}
